# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-06 07:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reg', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='party_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reg.Party'),
        ),
        migrations.AlterModelTable(
            name='party',
            table='party',
        ),
        migrations.AlterModelTable(
            name='post',
            table='post',
        ),
    ]
