# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-07 01:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reg', '0002_auto_20170806_0708'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='party_id',
            field=models.IntegerField(),
        ),
    ]
